import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import './ratecityGlobal.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RateCity',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" data-theme="ratecity">
      <head>
        <link rel="icon" href="/ratecity-favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
